# Generated by Django 5.2.6 on 2025-12-03 20:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('summary', models.TextField(help_text="Résumé court pour la page d'accueil", verbose_name='Résumé')),
                ('content', models.TextField(help_text="Contenu complet de l'actualité", verbose_name='Contenu')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de publication')),
                ('image', models.URLField(blank=True, help_text="URL de l'image", max_length=500, null=True, verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_featured', models.BooleanField(default=False, help_text="Afficher sur la page d'accueil", verbose_name='Mise en avant')),
                ('is_published', models.BooleanField(default=True, help_text='Actualité visible publiquement', verbose_name='Publié')),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
