# Generated by Django 5.2.6 on 2025-12-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actualite',
            options={'ordering': ['-date'], 'verbose_name': 'Actualité', 'verbose_name_plural': 'Actualités'},
        ),
        migrations.RemoveField(
            model_name='actualite',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='actualite',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='actualite',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='actualite',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='actualite',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='actualite',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='actualites/', verbose_name='Image'),
        ),
    ]
