# Generated by Django 6.0 on 2025-12-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualite', '0002_alter_actualite_options_remove_actualite_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualite',
            name='content_en',
            field=models.TextField(blank=True, help_text="Contenu complet de l'actualité en anglais (optionnel)", null=True, verbose_name='Contenu (EN)'),
        ),
        migrations.AddField(
            model_name='actualite',
            name='title_en',
            field=models.CharField(blank=True, help_text='Titre en anglais (optionnel)', max_length=200, null=True, verbose_name='Titre (EN)'),
        ),
        migrations.AlterField(
            model_name='actualite',
            name='content',
            field=models.TextField(help_text="Contenu complet de l'actualité en français", verbose_name='Contenu (FR)'),
        ),
        migrations.AlterField(
            model_name='actualite',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titre (FR)'),
        ),
    ]
